spring:
  profiles:
    include:
      - db
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
logging:
  level:
    com.example: debug
server:
  servlet:
    context-path: /