spring:
  profiles:
    include:
      - db
      - import
      - sms
      - rsa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    com.example: debug
server:
  servlet:
    context-path: /